services:
  docker.api:
    image: dockerapi-image
    container_name: dockerapi-container-v1
    build:
      context: .
      dockerfile: Docker.Api/Dockerfile
  docker2.api:
    image: docker2api-image
    container_name: docker2api-container-v1
    build:
      context: .
      dockerfile: Docker2.Api/Dockerfile
  sqlserver.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver.db
    restart: always
    environment:
     SA_PASSWORD: Password12*
     ACCEPT_EULA: "Y"
    ports: 
     - "1433:1433"
    volumes:
     - sqlserver-data-dockerapi1:/var/opt/mssql