services:
  docker.api:
    image: dockerapi-image
    container_name: dockerapi-container-v1
    build:
      context: .
      dockerfile: Docker.Api/Dockerfile
  docker2.api:
    image: docker2api-image
    container_name: docker2api-container-v1
    build:
      context: .
      dockerfile: Docker2.Api/Dockerfile
